export default function sitemap() {
  return [
    { url: 'https://beatbridge.live', lastModified: new Date() },
    { url: 'https://beatbridge.live/artists', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/currensy', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/harry-fraud', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/top', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/500-5k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/5k-10k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/10k-15k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/15k-20k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/20k-25k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/25k-30k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/30k-35k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/35k-40k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/40k-50k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/500-5k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/5k-10k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/10k-15k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/15k-20k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/20k-25k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/25k-30k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/30k-35k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/35k-40k', lastModified: new Date() },
    { url: 'https://beatbridge.live/artist/wheezy/network/40k-50k', lastModified: new Date() },
    { url: 'https://beatbridge.live/why-beatbridge', lastModified: new Date() },
    { url: 'https://beatbridge.live/privacy', lastModified: new Date() },
    { url: 'https://beatbridge.live/terms', lastModified: new Date() },
  ];
}
