import Link from "next/link";
import type { Metadata } from "next";

export const revalidate = 0;

export const metadata: Metadata = {
  title: "Why BeatBridge — The Smarter Way to Network as a Beatmaker",
  description:
    "BeatBridge maps the real social networks of established artists. Stop cold DMing strangers — start reaching the people who already have access.",
};

const PAIN_POINTS = [
  {
    title: "Generic contact databases",
    body: "Tools like MajorContacts or MusicMissile give you lists of random A&Rs and managers. They don't know you. They don't know your sound. They get hundreds of cold pitches a day.",
  },
  {
    title: "Spray and pray DMs",
    body: "Sending the same beat link to 500 people hoping someone bites. No context, no relationship, no reason for them to care.",
  },
  {
    title: "Chasing the wrong people",
    body: "DMing artists with 500K followers who never read their messages. The gatekeepers are the people around them — not the artists themselves.",
  },
];

const DIFFERENTIATORS = [
  {
    title: "Real social networks, not random databases",
    body: "Every contact on BeatBridge is someone an established artist personally follows. That's a warm connection — not a cold list.",
  },
  {
    title: "AI-personalized DMs, not copy-paste templates",
    body: "Tell us your style, your influences, your story. Our AI writes a DM that sounds like you — tailored to each contact's background and role.",
  },
  {
    title: "Ranked by response probability",
    body: "We score every contact based on follower count and availability. Smaller accounts reply faster. We tell you exactly who to reach out to first.",
  },
  {
    title: "Built by a beatmaker, for beatmakers",
    body: "Not a corporate tool. Not a generic CRM. BeatBridge was built by someone who has the same problem you do — and decided to solve it.",
  },
];

const COMPETITORS = [
  {
    name: "Producerfury",
    description:
      "A CRM for producers with Instagram artist search and beat pack automation. Useful for managing contacts — but their approach is find random artists matching filters. They don't map who your favorite artists actually know and trust.",
    advantage:
      "We don't give you a list of strangers. We give you the real inner circle of established artists.",
  },
  {
    name: "MajorContacts / MusicMissile",
    description:
      "Static databases of industry contacts — A&Rs, managers, labels. Thousands of names, no context. You're cold DMing people who get hundreds of pitches a day and have no idea who you are.",
    advantage:
      "Our contacts already have a relationship with the artist you're trying to reach. That's the difference between cold and warm.",
  },
  {
    name: "AutoReacher",
    description:
      "Instagram DM automation tool. Sends bulk messages automatically — and risks getting your account banned by Meta. Fast volume, zero personalization.",
    advantage:
      "We help you send fewer, better DMs. Quality over quantity. No ban risk.",
  },
  {
    name: "Kits4Beats",
    description:
      "Sells static lists of Instagram contacts who worked on tracks by major artists. No AI, no personalization, no ranking — just a spreadsheet.",
    advantage:
      "Our contacts are live, ranked by response probability, and each DM is generated by AI based on your specific profile.",
  },
];

const TABLE_ROWS = [
  { feature: "Contacts from real artist networks",  producerfury: false, majorcontacts: false, autoreacher: false },
  { feature: "AI-personalized DMs per contact",     producerfury: false, majorcontacts: false, autoreacher: false },
  { feature: "Response probability scoring",        producerfury: false, majorcontacts: false, autoreacher: false },
  { feature: "No ban risk",                         producerfury: true,  majorcontacts: true,  autoreacher: false },
  { feature: "Built for beatmakers",                producerfury: true,  majorcontacts: false, autoreacher: false },
  { feature: "Free to start",                       producerfury: false, majorcontacts: false, autoreacher: false },
  { feature: "Social proximity networking",         producerfury: false, majorcontacts: false, autoreacher: false },
  { feature: "2-step DM strategy built-in",         producerfury: false, majorcontacts: false, autoreacher: false },
];

function Check({ yes }: { yes: boolean }) {
  return yes
    ? <span className="text-green-400 font-bold">✅</span>
    : <span className="text-[#404040]">❌</span>;
}

export default function WhyBeatBridgePage() {
  return (
    <div className="min-h-screen bg-[#080808]">
      <div className="max-w-4xl mx-auto px-4 py-16 sm:py-24">

        {/* ── HERO ─────────────────────────────────────────────────── */}
        <div className="text-center mb-20 scroll-animate">
          <div className="inline-flex items-center gap-2 bg-orange-500/10 border border-orange-500/20 rounded-full px-4 py-1.5 text-orange-400 text-xs font-semibold uppercase tracking-[0.12em] mb-6">
            The BeatBridge Difference
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-light tracking-[0.02em] leading-tight mb-6">
            Stop cold DMing strangers.{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-[#f85c00]">
              Start reaching people who already know your world.
            </span>
          </h1>
          <p className="text-[#a0a0a0] text-lg max-w-2xl mx-auto leading-relaxed">
            Every other tool gives you a list of random industry contacts. BeatBridge maps the real social network of established artists — the people they actually follow, trust, and work with.
          </p>
        </div>

        {/* ── THE PROBLEM ──────────────────────────────────────────── */}
        <section className="mb-20 scroll-animate">
          <h2 className="text-2xl sm:text-3xl font-light tracking-[0.02em] mb-2">
            The old way doesn&apos;t work.
          </h2>
          <p className="text-[#606060] text-sm mb-8">Sound familiar?</p>

          <div className="grid sm:grid-cols-3 gap-4">
            {PAIN_POINTS.map(({ title, body }) => (
              <div
                key={title}
                className="bg-white/[0.025] border border-white/[0.08] rounded-2xl p-5"
              >
                <p className="text-base mb-3">❌</p>
                <p className="text-white font-semibold text-sm mb-2">{title}</p>
                <p className="text-[#a0a0a0] text-sm leading-relaxed">{body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── THE BEATBRIDGE WAY ────────────────────────────────────── */}
        <section className="mb-20 scroll-animate">
          <h2 className="text-2xl sm:text-3xl font-light tracking-[0.02em] mb-3">
            The smarter approach:{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-[#f85c00]">
              Social proximity networking.
            </span>
          </h2>
          <p className="text-[#a0a0a0] text-base leading-relaxed mb-8 max-w-2xl">
            We map who established artists actually follow on Instagram — their engineers, managers, producers, close circle. These people have direct access to the artists you want to reach. And they actually read their DMs.
          </p>

          <div className="grid sm:grid-cols-2 gap-4">
            {DIFFERENTIATORS.map(({ title, body }) => (
              <div
                key={title}
                className="bg-white/[0.025] border border-orange-500/[0.15] rounded-2xl p-5 hover:border-orange-500/30 transition-colors"
              >
                <p className="text-orange-500 text-base mb-3">✦</p>
                <p className="text-white font-semibold text-sm mb-2">{title}</p>
                <p className="text-[#a0a0a0] text-sm leading-relaxed">{body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── COMPETITORS ──────────────────────────────────────────── */}
        <section className="mb-20 scroll-animate">
          <h2 className="text-2xl sm:text-3xl font-light tracking-[0.02em] mb-8">
            How BeatBridge compares to what&apos;s out there
          </h2>

          <div className="space-y-4">
            {COMPETITORS.map(({ name, description, advantage }) => (
              <div
                key={name}
                className="bg-white/[0.025] border border-white/[0.08] rounded-2xl p-5"
              >
                <p className="text-white font-bold text-sm mb-2">{name}</p>
                <p className="text-[#707070] text-sm leading-relaxed mb-3">{description}</p>
                <div className="flex items-start gap-2 bg-orange-500/[0.08] border border-orange-500/20 rounded-xl px-3 py-2">
                  <span className="text-orange-400 font-bold text-xs flex-shrink-0 mt-0.5">BB →</span>
                  <p className="text-orange-300/90 text-xs leading-relaxed">{advantage}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── COMPARISON TABLE ─────────────────────────────────────── */}
        <section className="mb-20 scroll-animate">
          <h2 className="text-xl font-light tracking-[0.02em] mb-6 text-[#a0a0a0]">
            Feature comparison
          </h2>

          <div className="overflow-x-auto rounded-2xl border border-white/[0.08]">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/[0.08] bg-white/[0.025]">
                  <th className="text-left px-4 py-3 text-[#606060] font-medium text-xs uppercase tracking-[0.08em]">Feature</th>
                  <th className="px-3 py-3 text-center text-[#606060] font-medium text-xs uppercase tracking-[0.08em]">Producerfury</th>
                  <th className="px-3 py-3 text-center text-[#606060] font-medium text-xs uppercase tracking-[0.08em]">MajorContacts</th>
                  <th className="px-3 py-3 text-center text-[#606060] font-medium text-xs uppercase tracking-[0.08em]">AutoReacher</th>
                  <th className="px-3 py-3 text-center text-orange-400 font-bold text-xs uppercase tracking-[0.08em]">BeatBridge</th>
                </tr>
              </thead>
              <tbody>
                {TABLE_ROWS.map(({ feature, producerfury, majorcontacts, autoreacher }, i) => (
                  <tr
                    key={feature}
                    className={`border-b border-white/[0.04] ${i % 2 === 0 ? "" : "bg-white/[0.01]"}`}
                  >
                    <td className="px-4 py-3 text-[#a0a0a0] text-xs">{feature}</td>
                    <td className="px-3 py-3 text-center text-base"><Check yes={producerfury} /></td>
                    <td className="px-3 py-3 text-center text-base"><Check yes={majorcontacts} /></td>
                    <td className="px-3 py-3 text-center text-base"><Check yes={autoreacher} /></td>
                    <td className="px-3 py-3 text-center text-base"><Check yes={true} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* ── CLOSING STATEMENT ────────────────────────────────────── */}
        <section className="mb-20 scroll-animate">
          <div className="bg-white/[0.025] border border-orange-500/[0.15] rounded-2xl p-6 sm:p-8 text-center">
            <p className="text-white/80 text-base sm:text-lg leading-relaxed max-w-2xl mx-auto">
              Every other tool treats networking like a numbers game. BeatBridge treats it like what it actually is:{" "}
              <span className="text-orange-400 font-semibold">relationship building through social proximity.</span>{" "}
              The people around your favorite artists are your real gateway — not cold databases.
            </p>
          </div>
        </section>

        {/* ── CTA ──────────────────────────────────────────────────── */}
        <section className="text-center scroll-animate">
          <h2 className="text-3xl sm:text-4xl font-light tracking-[0.02em] mb-4">
            Ready to network smarter?
          </h2>
          <p className="text-[#a0a0a0] text-base mb-8">
            Start with our free artist networks — no credit card required.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/artists"
              className="w-full sm:w-auto text-center text-sm font-semibold bg-gradient-to-br from-[#f97316] to-[#f85c00] text-white px-8 py-3 rounded-lg hover:opacity-90 hover:scale-[1.02] transition-all duration-200"
            >
              Explore Networks →
            </Link>
            <Link
              href="/artists"
              className="w-full sm:w-auto text-center text-sm font-medium text-[#a0a0a0] hover:text-white transition-colors"
            >
              See our artist roster →
            </Link>
          </div>
        </section>

      </div>

      {/* Footer */}
      <footer className="border-t border-white/[0.05] py-12 px-4 text-center text-[#404040] text-sm">
        <p className="font-medium text-white mb-1.5 tracking-wide">
          Beat<span className="text-orange-500">Bridge</span>
        </p>
        <p>© 2025 BeatBridge. Built for the independent grind.</p>
        <p className="mt-2.5 flex items-center justify-center gap-3 flex-wrap">
          <Link href="/why-beatbridge" className="hover:text-[#a0a0a0] transition-colors">Why BeatBridge</Link>
          <span>·</span>
          <Link href="/privacy" className="hover:text-[#a0a0a0] transition-colors">Privacy Policy</Link>
          <span>·</span>
          <Link href="/terms" className="hover:text-[#a0a0a0] transition-colors">Terms of Service</Link>
        </p>
      </footer>
    </div>
  );
}
